# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8e327c43a7dc4b404f1c33c8c16f8d5d124ca21facee4ebe3f75caa3dce3f9d7a01b636180d9a0dc343a451aa26fc2fe14d319685d5558a5b1c4e2f7a5bef7f

test:
  secret_key_base: 638aad8026238569f9c47d92cf88c0e08271db2b5e2f82477c1906bcddc52a1d0b3ec95bbd164fd44b0315428754ab25d0efa763f5dccb8948ce89d18abba1aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
